### PR TITLE
silabs: siwg917: Fix memory definitions

### PR DESCRIPTION
**Pull request by jhedberg**
Fix the unit path definitions for flash and RAM, and make sure the board
yaml file is in sync with DTS.

### CODE REVIEW

**Comment by jhedberg** [comment]
@jerome-pouiller any comments on this one? Making the DT node unit path match the `reg` property should hopefully be non-controversial, since upstream CI will fail otherwise. As for the indicated amount of RAM, I took that from the 917 specs (there are configurations supporting more, but going with the lowest RAM config should be a safe choice for now).

**Comment by jerome-pouiller** [comment]
I believe I have copied the memory addresses from the linker file of WiseConnect. I am going to check that this morning.

**Comment by jhedberg** [comment]
> I believe I have copied the memory addresses from the linker file of WiseConnect. I am going to check that this morning.

Note that I'm not really changing the addresses, rather just making sure that the DT node unit address is in sync with the `reg` property. Generally, it's the `reg` property value that gets used (which I'm not changing), so syncing the unit address with it shouldn't make any other difference except making DTS syntax checkers happy.

**Comment by jhedberg** [comment]
> > I believe I have copied the memory addresses from the linker file of WiseConnect. I am going to check that this morning.
> 
> Note that I'm not really changing the addresses, rather just making sure that the DT node unit address is in sync with the `reg` property. Generally, it's the `reg` property value that gets used (which I'm not changing), so syncing the unit address with it shouldn't make any other difference except making DTS syntax checkers happy.

Sorry, I realized that I *am* actually changing `reg` for the other node here. However, at least in my testing I didn't see any breakage.

**Comment by jerome-pouiller** [comment]
In my linker file, I have found:
```
 MEMORY
 {
   rom   (rx)  : ORIGIN = 0x81c2000, LENGTH = 0x6e000
   ram   (rwx) : ORIGIN = 0xc, LENGTH = 0x2fc00
   psram (rwx) : ORIGIN = 0xa000000, LENGTH = 0x800000
 }
 MEMORY
 {
   udma0   (rwx)  : ORIGIN = 0x2fc00, LENGTH = 0x400
   udma1   (rwx)  : ORIGIN = 0x24061c00, LENGTH = 0x400
 }
```
`0x2fc00 == 191kB`. Probably we could use `<0 DT_SIZE_K(192)>` and properly declare `udma0`. However, for now I am not super comfortable with this change.

**Comment by jhedberg** [comment]
> > `0x2fc00 == 191kB`. Probably we could use `<0 DT_SIZE_K(192)>` and properly declare `udma0`. However, for now I am not super comfortable with this change.
> 
> Ok, but then at least the unit address needs fixing, i.e. it should be `memory@0` instead of `memory@400`

@jerome-pouiller now updated, please take another look

**Review by jerome-pouiller — APPROVED** [review]

**Pull request merged**
