### PR TITLE
github: workflows: Remove continue-on-error

### PR DESCRIPTION
**Pull request by jhedberg**
We want the workflows to fail for these steps, so remove continue-on-error.

### CODE REVIEW

**Review by asmellby — APPROVED** [review]

**Comment by jhedberg** [comment]
Note: I'll wait until https://github.com/zephyrproject-rtos/zephyr/pull/80537 has been merged, and then update `west.yml` in this PR, since otherwise our merge policy will prevent merging due to the failing checks.

**Review by jerome-pouiller — APPROVED** [review]

**Review by jerome-pouiller — APPROVED** [review]

**Comment by jerome-pouiller** [comment]
The build fails on windows. Probably I shouldn't removed this snippet:

          if [ "${{ runner.os }}" = "Windows" ]; then
            EXTRA_TWISTER_FLAGS="--short-build-path -O/tmp/twister-out"
          fi

**Comment by jhedberg** [comment]
> The build fails on windows. Probably I shouldn't removed this snippet:
> 
> ```
>       if [ "${{ runner.os }}" = "Windows" ]; then
>         EXTRA_TWISTER_FLAGS="--short-build-path -O/tmp/twister-out"
>       fi
> ```

Indeed. That said, do we think it really adds sufficient value to have macOS and Windows in the CI?. I would expect that upstream takes care of testing that the SDK works on all three platforms. That said, if we ever start introducing non-Zephyr SDK dependencies to our CI workflows (say, Commander or JLink), then I think it'd be important to check that the steps still work on all Zephyr SDK supported operating systems.

**Comment by jerome-pouiller** [comment]
The failure on Windows is not introduced by this PR. So, I suggest to merge it.

**Comment by jhedberg** [comment]
> The failure on Windows is not introduced by this PR. So, I suggest to merge it.

I'd have to tweak the repo settings first, since right now it's set so that even an admin can't press the Merge button when there's a failed Check. I went with disabling Windows and macOS instead for now. We can re-enable them later if there's a clear justification for it.

**Pull request merged**
